name: Bug Report
about: Create a bug report for sentry-expo
issue_body: true
inputs:
  - type: description
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: description
    attributes:
      value: If you leave out sections there is a high likelihood your issue will be closed. If you have a question, not a bug report, please post it on our [forums](https://forums.expo.io/) instead.
  - type: input
    attributes:
      label: Summary
      description: 'Describe the issue in 1 or 2 sentences'
      required: true
  
